version: '3'
services:
  server:
    image: student122/backend-image:latest
    container_name: voting-app-server
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - voting-app-network

  client:
    image: student122/frontend-image:latest
    container_name: voting-app-client
    ports:
      - "3001:3001"
    networks:
      - voting-app-network

  redis:
    image: "redis:alpine"
    container_name: voting-app-redis
    ports:
      - "6379:6379"
    networks:
      - voting-app-network

networks:
  voting-app-network:
    driver: bridge
